### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by pippinsplugins** [realbigplugins/edd-fields#71] opened 2017-07-03 19:19 UTC
On a product that was submitted through the FES Vendor Dashboard, I'm getting the following warning / notice:

Invalid argument supplied for foreach()
wp-content/plugins/edd-fields/core/admin/class-edd-fields-post-edit.php:164

Undefined index: custom
wp-content/plugins/edd-fields/core/admin/class-edd-fields-post-edit.php:164

**Comment by d4mation** [comment] 2017-07-13 17:38
I wasn't able to reproduce that specific error, but I believe I've implemented a fix.

Could someone check the `issue/71/invalid-argument-custom-template` branch for me to confirm?

I did the following:
- Created a Download as a Vendor user using the Frontend Form
- Switched to my Admin account
- Went to the Admin Post Edit screen for the Download, no error found

**Comment by d4mation** [comment] 2017-07-13 19:48
Ah, I wasn't seeing the error because it only shows if you choose "Custom". Merged in.

**Closed by d4mation** 2017-07-13 19:48 UTC
Labels: bug
